---
- hosts: localhost
  become: true
  connection: local
  vars:
  tasks:
    - name: Updating APK Cache
      apk:
        update_cache: yes

    - name: Installing Jenkins Pre-Reqs
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'bash'

    - name: Checking For Jenkins User
      shell: "cut -d: -f1 /etc/passwd"
      register: "users_list"

    - name: Creating Jenkins User
      command: "adduser -h '{{ jenkins_home }}' -s /bin/bash -D jenkins"
      when: users_list.stdout.find('jenkins') != 1

    - name: Ensuring Folders Exist
      file:
        path: "{{ jenkins_home }}"
        state: "directory"
        owner: "jenkins"
        group: "jenkins"

    - name: Ensuring Jenkins Permissions Are Correct
      file:
        path: "{{ jenkins_home }}"
        state: "directory"
        recurse: yes
        owner: "jenkins"
        group: "jenkins"
